/*KLUDGE: Mixins can't be used by different mods, so this class that contains ALL the mixin code in the KAI library is needed. You need to inherit from this
if you want to make something that's not an NPC, but can still use the mixin code the library includes.*/
Class KAI_MixinActor : Actor Abstract
{
	Mixin KAI_MathFunctions;
	Mixin KAI_UniversalFunctions;
	Mixin KAI_CheckFunctions;
}

Class KAI_Actor : Actor Abstract
{
}